server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_db?createDatabaseIfNotExist=true
    username: root
    password: 112224448
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace